ckpts:
  - original_joker_301_checkpoint0.pt
  - original_frida-kahlo_301_checkpoint0.pt
  - original_petrus-christus_301_checkpoint0.pt
  - original_disney_301_checkpoint0.pt
  - original_sketch_301_checkpoint0.pt
  - original_avatar_301_checkpoint0.pt
  - original_botticelli_301_checkpoint0.pt
  - original_elf_301_checkpoint0.pt
  - original_posion-ivy_301_checkpoint0.pt
n_examples: 7
img_size: 256
latents_dir: example_latents/basic
checkpoints_dir: checkpoints/original_coefs
res_name: 5styles.png
style_mixing:
  alpha: 0
  inversion_type: e4e
n_samples: 1000
batch_size: 20
device: cuda