ckpts:
    - original_joker_301_checkpoint0.pt
    - original_frida-kahlo_301_checkpoint0.pt
    - original_petrus-christus_301_checkpoint0.pt
    - original_sketch_301_checkpoint0.pt
    - original_disney_301_checkpoint0.pt
    - original_avatar_301_checkpoint0.pt
n_examples: 7
img_size: 256
latents_dir: example_latents
checkpoints_dir: checkpoints
res_name: 5styles.png
