exp:
  config_dir: configs
  config: im2im_single.yaml
  project: test_project
  tags:
    - test
  name: test_run_difa
  seed: 0
  root: .
  notes: empty notes
  logging: true
  step_save: 25
  trainer: im2im_difa
  checkpoint_dir: checkpoints
  ckpt_name : exp.pt
training:
  iter_num: 301
  batch_size: 2
  device: cuda:0
  generator: stylegan2
  phase: all
  da_type: parametrization
  stylemix_latent: 3
  source_class: Real Person
  target_class: ./styles/joker.jpeg
  auto_layer_k: 16
  auto_layer_iters: 0
  auto_layer_batch: 8
  mixing_noise: 0.0
  clip_layer: 3
  model_type: 'difa'
emb:
  type: 'proj'
  num: 16
  online_truncation: 0.8
  src_emb_dir: 'clip_means'
inversion:
  method: e4e
  method_for_latent: e4e
  align_style: False
  model_path: pretrained/e4e_ffhq_encode.pt
  latents_root: 'latents_inversion_training'
optimization_setup:
  visual_encoders:
    - ViT-B/32
    - ViT-B/16
  loss_funcs:
    - direction
    - difa_w
    - difa_local
    - dom_div
  loss_coefs:
    - 1.0
    - 6.0
    - 1.0
    - 1.0
  num_keep_first: 7
  psp_alpha: 0.6
  face_rec_path: pretrained/model_ir_se50.pth
  g_reg_every: 4
  optimizer:
    weight_decay: 0.0
    lr: 0.02
    betas:
      - 0.0
      - 0.999
  scheduler:
    n_steps: 20
    start_lr: 0.001
generator_args:
  checkpoint_path: pretrained/stylegan2-ffhq-config-f.pt
evaluation:
  is_on: false
  vision_models:
    - ViT-B/32
    - ViT-B/16
  step: 200
  data_size: 500
  batch_size: 24
  fid: true
  fid_ref: ../few-shot-gan-adaptation/sketches_all_resized/
logging:
  enabled: true
  log_every: 10
  log_images: 20
  latents_to_edit: [ ]
  truncation: 0.7
  num_grid_outputs: 1
checkpointing:
  is_on: false
  start_from: false
  step_backup: 500
